# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8979f81563418f6af35c70400e553891a757bb79a882aa5f7ad4b2275ca5b34accb95bf5ff6e833808df814189fd8829aeab6e80601cc6956a3694b63cba5b7

test:
  secret_key_base: de6eb4b8eaaa3de692b6d116ede83370575a13f96fec05823fc8b6167ad5d4b0da8b12361e6eee5d43551f9a9ff55212accdb6b58d76e4bed6be4846853ce089

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
